### ISSUE TITLE
实习邀请

### ISSUE THREAD

**Issue by zhouyanjun90** [FlYWMe/SearchServer#2]
有兴趣来微博做faiss相关实习吗？

**Comment by FlYWMe** [comment]
您好，我对贵司的实习机会很感兴趣，有机会想深入了解一下实习要求等具体情况，谢谢。

**Comment by FlYWMe** [comment]
您好，我对贵司的实习机会很感兴趣，有机会想深入了解一下实习要求等具体情况，谢谢。

**Comment by zhouyanjun90** [comment]
你可以加下我的微信：13718889033
